# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: "unosoruso"

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: ""

menu:
  - { name: "Acerca de", url: "acerca-de" }
  - { name: "Webs amigas", url: "otras-webs" }
  - { name: "Recursos y descargas", url: "recursosdescargas" }
  - { name: "Contacto", url: "contacto" }

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
  - { icon: "twitter", link: "https://twitter.com/unosoruso" }
  - { icon: "facebook", link: "https://www.facebook.com/unosoruso" }
  - { icon: "instagram", link: "https://instagram.com/unosoruso" }
  - { icon: "envelope", link: "mailto:hello@unosoruso.com" }
  - { icon: "rss-square", link: "feed.xml" }
# - {icon: 'rss-square', link: 'rss-feed.xml'}

# Customize site text
pagination:
  next_page: "Siguiente"
  previous_page: "Atrás"

sharing_button_prompt: "¡Compartir ayuda mucho!"

related_posts: "Quizás también te guste..."

post_date_prefix: "Escrito el"
